### PR TITLE
Lp 5.0

### PR DESCRIPTION
**Pull request by Gorneman**
Thanks for your work. I simply merged some modification I think are useful. F2FS from LeanKernel. It is more up to date .

### CODE REVIEW

**Comment by jfmcbrayer** [comment]
Hi. I only just saw your pull requests. Have you closed them because you're going to be giving an updated one? Or shall I reopen this one?

**Comment by Gorneman** [comment]
Hi, I closed it because it build fine, boot fine, works fine, but when i 
try to see an embedded video, it reboots. At this moment I can't find 
what is the problem, in the weekend i'll try to understand more

Il 21/01/2015 13:57, jfmcbrayer ha scritto:

> Hi. I only just saw your pull requests. Have you closed them because 
> you're going to be giving an updated one? Or shall I reopen this one?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/jfmcbrayer/grouper-kernel/pull/2#issuecomment-70831993.

 --
 ZE-Light e ZE-Pro: servizi zimbra per caselle con dominio email.it, per tutti i dettagli 
Clicca qui http://posta.email.it/caselle-di-posta-z-email-it/?utm_campaign=email_Zimbra_102014=main_footer/f

 Sponsor:
 Soluzioni di email hosting per tutte le esigenze: dalle caselle gratuite a quelle professionali su piattaforma Zimbra, da quelle su proprio dominio a quelle certificate PEC. Confronta le soluzioni
 Clicca qui: http://adv.email.it/cgi-bin/foclick.cgi?mid=13325&d=21-1

**Comment by jfmcbrayer** [comment]
Domenico Di Misa writes:

> Hi, I closed it because it build fine, boot fine, works fine, but when i 
> try to see an embedded video, it reboots. At this moment I can't find 
> what is the problem, in the weekend i'll try to understand more

Could you be overclocking or undervolting? I've noticed that in LP, my
setting of a 1.3GHz max clock is not sticking, and it is reverting to
1.5GHz. I may have to revert the overclocking patches if I can't find a
solution (including the power.grouper.so that I included previously does
not seem do the job).

**Comment by Gorneman** [comment]
I use Rastapop rom, smartmax with cpu 102 Mhz -1,2  Ghz , ROW and a little bit of undervolt . But I tested also with default kernel values.

**Comment by Gorneman** [comment]
I have build a new image with slub and only f2fs commits, same problem.

**Comment by jfmcbrayer** [comment]
Have you tried building just from the head of my tree, to see if it's your commits causing the problem?

**Comment by Gorneman** [comment]
no, but I used your kernel without this problem.

**Comment by jfmcbrayer** [comment]
I want to rule out your build environment.

**Comment by Gorneman** [comment]
Mint 17.1 64 bit and arm-cortex_a9-linux-gnueabihf-linaro_4.9.3-2015.01toolchain

**Pull request closed without merging**
