### PR TITLE
Lp 5.0 f2fs update

### PR DESCRIPTION
**Pull request by Gorneman**
I have merged new f2fs version and it works. I'm using it with rastapop 5.1

### CODE REVIEW

**Comment by Gorneman** [comment]
problem with video stream

**Comment by jfmcbrayer** [comment]
Please let me know when you get this working, and I'll be happy to add it.

**Comment by Gorneman** [comment]
I'll try to understand what's the problem.

**Comment by Gorneman** [comment]
i found the solution: SLAB instead of SLUB in defconfig 
"CONFIG_SLAB=y"
"# CONFIG_SLUB is not set"
make a new branch, merge and test it.

**Comment by jfmcbrayer** [comment]
I'm testing now; so far, so good. I don't currently have the means to actively test f2fs; how is your testing?

**Comment by Gorneman** [comment]
fine until now, i will continue the test to look for bugs or problems.

**Comment by jfmcbrayer** [comment]
I've pushed the changes from the initial pull request. These other changes you might want to put into another pull request or another series of them. Thanks for your help.

**Comment by Gorneman** [comment]
http://www.mediafire.com/download/xy6bpetp4fs0sf6/grouper-carcosa_defconfig
this is my defconfig. There are some little changes to include.

**Comment by Gorneman** [comment]
http://www.mediafire.com/download/ejyh1a1o9iq675i/grouper-carcosa_defconfig
I have changed some things in defconfig. Please, check them and include, if you think they are useful.
I'm doing some "experiment". When ready, I will put another pull request. Thanks

**Comment by jfmcbrayer** [comment]
I'll try when I can. Thanks for your work.

**Pull request closed without merging**
